version: '3.8'

services:
    server:
        container_name: fastapi_boilerplate_server
        build: .
        depends_on:
            - postgres
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/app
        env_file: .env.dev
        command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

    postgres:
        container_name: fastapi_boilerplate_postgres
        image: postgres:alpine
        environment:
            POSTGRES_DB: template
            POSTGRES_USER: root
            POSTGRES_PASSWORD: toor
        ports:
            - '5432:5432'

networks:
    default:
        name: fastapi_boilerplate_network
